#!/usr/bin/env bash

battery_path="/sys/class/power_supply/BAT1"

battery_percentage=$(cat "$battery_path/capacity")
battery_state=$(cat "$battery_path/status")

if [[ "$battery_state" == "Charging" ]]; then
  icon=" "
elif [[ "$battery_percentage" -ge 80 ]]; then
  icon=" "
elif [[ "$battery_percentage" -ge 60 ]]; then
  icon=" "
elif [[ "$battery_percentage" -ge 40 ]]; then
  icon=" "
elif [[ "$battery_percentage" -ge 20 ]]; then
  icon=" "
else
  icon=" "
fi

echo -n "$icon $battery_percentage%"
